export const WORDS = [
  {
    id: "liquidity",
    term: "liquidity",
    phonetic: "/lɪˈkwɪdəti/",
    pos: "n.",
    topic: "finance",
    meaning: "流动性：资产能较快变现、且价格不大幅下跌的能力。",
    grammar: "不可数名词。常见搭配：liquidity risk（流动性风险）、liquidity crunch（流动性紧张）。",
    contextKind: "news",
    contextTitle: "市场简报",
    contextBody: "The treasurer said overnight liquidity remained adequate, even as credit spreads widened.",
    contextZh: "司库表示隔夜流动性仍然充足，尽管信用利差已经走阔。",
  },
  {
    id: "amortization",
    term: "amortization",
    phonetic: "/əˌmɔːrtɪˈzeɪʃn/",
    pos: "n.",
    topic: "finance",
    meaning: "摊销：把无形资产成本在受益期内分摊计入费用。",
    grammar: "与 depreciation（折旧，多用于固定资产）相对。动词是 amortize。",
    contextKind: "story",
    contextTitle: "关账夜",
    contextBody: "Before midnight, she double-checked the amortization schedule so the software license would not hit one quarter all at once.",
    contextZh: "午夜前，她又核对了一遍摊销表，以免软件许可费一次性全部计入某个季度。",
  },
  {
    id: "accrual",
    term: "accrual",
    phonetic: "/əˈkruːəl/",
    pos: "n.",
    topic: "finance",
    meaning: "权责发生制下的应计：收入或费用已发生但尚未收付。",
    grammar: "accrual accounting 与 cash accounting 相对。动词 accrue。",
    contextKind: "news",
    contextTitle: "审计备忘",
    contextBody: "The audit team asked why bonus accrual was booked in December when the board vote was still pending.",
    contextZh: "审计组问，董事会尚未表决，为什么十二月就计提了奖金应计。",
  },
  {
    id: "covenant",
    term: "covenant",
    phonetic: "/ˈkʌvənənt/",
    pos: "n.",
    topic: "finance",
    meaning: "契约条款：贷款合同里约束借款人的财务或行为条件。",
    grammar: "可数名词。break a covenant（违反契约）。形容词 covenanted 较少用。",
    contextKind: "speech",
    contextTitle: "信贷例会",
    contextBody: "If we miss the interest coverage covenant, the bank can reprice the facility within ten business days.",
    contextZh: "如果我们达不到利息覆盖率契约，银行可以在十个工作日内重定价这笔授信。",
  },
  {
    id: "hedge",
    term: "hedge",
    phonetic: "/hedʒ/",
    pos: "v./n.",
    topic: "finance",
    meaning: "对冲：用衍生品或反向头寸降低价格、利率或汇率风险。",
    grammar: "动词 hedge against risk；名词 a currency hedge。",
    contextKind: "news",
    contextTitle: "外汇窗口",
    contextBody: "The company hedged next year's dollar receivables after the currency swung four percent in a week.",
    contextZh: "汇率一周波动了四个百分点后，公司对冲了明年的美元应收账款。",
  },
  {
    id: "working-capital",
    term: "working capital",
    phonetic: "/ˈwɜːrkɪŋ ˈkæpɪtl/",
    pos: "n.",
    topic: "finance",
    meaning: "营运资本：流动资产减去流动负债，衡量短期周转能力。",
    grammar: "不可数。公式常说 working capital = current assets − current liabilities。",
    contextKind: "story",
    contextTitle: "供应紧张",
    contextBody: "Inventory piled up, and working capital tightened even though sales looked healthy on paper.",
    contextZh: "库存堆了起来，账面上销售看起来不错，营运资本却更紧了。",
  },
  {
    id: "ebitda",
    term: "EBITDA",
    phonetic: "/iːˈbɪtdə/",
    pos: "n.",
    topic: "finance",
    meaning: "息税折旧摊销前利润，常用来比较经营现金流近似值。",
    grammar: "缩写当作不可数名词。读字母或读作 ebit-da。",
    contextKind: "speech",
    contextTitle: "业绩会",
    contextBody: "We guided EBITDA margin up one point, but warned that amortization of new licenses will still hit net income.",
    contextZh: "我们把 EBITDA 利润率指引上调了一个点，但也提醒新许可的摊销仍会冲击净利润。",
  },
  {
    id: "impairment",
    term: "impairment",
    phonetic: "/ɪmˈpermənt/",
    pos: "n.",
    topic: "finance",
    meaning: "减值：资产可收回金额低于账面价值时确认的损失。",
    grammar: "take an impairment / record an impairment charge。动词 impair。",
    contextKind: "news",
    contextTitle: "年报摘录",
    contextBody: "Goodwill impairment of eighty million followed a weaker outlook in the payments segment.",
    contextZh: "支付业务前景转弱后，公司确认了八千万的商誉减值。",
  },
  {
    id: "leverage",
    term: "leverage",
    phonetic: "/ˈlevərɪdʒ/",
    pos: "n./v.",
    topic: "finance",
    meaning: "杠杆：用负债放大收益与风险；作动词也可表示“借助”。",
    grammar: "financial leverage 偏财务；在信息化语境里 leverage data 表示利用数据。",
    contextKind: "speech",
    contextTitle: "董事会",
    contextBody: "The CFO argued we should not add leverage just to hit a buyback target this quarter.",
    contextZh: "财务总监认为，不应只为了完成这季度回购目标而去加杠杆。",
  },
  {
    id: "provision",
    term: "provision",
    phonetic: "/prəˈvɪʒn/",
    pos: "n.",
    topic: "finance",
    meaning: "准备/拨备：为很可能发生的负债预先确认的费用，如坏账准备。",
    grammar: "make a provision for bad debts。注意与 supply 的“供应”义不同。",
    contextKind: "story",
    contextTitle: "风控晨会",
    contextBody: "After two large clients delayed payment, she increased the provision rather than waiting for year end.",
    contextZh: "两个大客户推迟付款后，她提高了拨备，而不是等到年底。",
  },
  {
    id: "yield",
    term: "yield",
    phonetic: "/jiːld/",
    pos: "n./v.",
    topic: "finance",
    meaning: "收益率：投资带来的回报率；动词也可表示产生、让步。",
    grammar: "bond yield、dividend yield。动词：the portfolio yielded 6%。",
    contextKind: "news",
    contextTitle: "债市收盘",
    contextBody: "Ten-year yields slipped after the data print, and swap desks reopened hedges into the close.",
    contextZh: "数据公布后十年期收益率回落，互换台在收盘前重新开了对冲。",
  },
  {
    id: "collateral",
    term: "collateral",
    phonetic: "/kəˈlætərəl/",
    pos: "n.",
    topic: "finance",
    meaning: "抵押品：借款时质押的资产，违约时可被处置。",
    grammar: "不可数。post collateral（提交抵押品）、collateralize a loan。",
    contextKind: "speech",
    contextTitle: "银团谈判",
    contextBody: "The lenders wanted extra collateral on receivables before they would extend the revolving line.",
    contextZh: "出借人要求对应收账款追加抵押，才肯展期循环额度。",
  },
  {
    id: "capex",
    term: "capex",
    phonetic: "/ˈkæpeks/",
    pos: "n.",
    topic: "finance",
    meaning: "资本支出：购置或改良长期资产的开支，与 opex（经营费用）相对。",
    grammar: "不可数或作修饰语：capex plan。全称 capital expenditure。",
    contextKind: "news",
    contextTitle: "投资计划",
    contextBody: "Cloud migration will lift this year's capex, but the CFO expects opex to fall from year two.",
    contextZh: "上云会抬高今年资本支出，但财务总监预计经营费用从第二年起下降。",
  },
  {
    id: "fair-value",
    term: "fair value",
    phonetic: "/fer ˈvæljuː/",
    pos: "n.",
    topic: "finance",
    meaning: "公允价值：市场参与者在有序交易中愿意成交的价格。",
    grammar: "fair value measurement；Level 1/2/3 inputs 是常见分层。",
    contextKind: "story",
    contextTitle: "估值争论",
    contextBody: "Without an active market, they had to defend the fair value of the unlisted stake with a model.",
    contextZh: "没有活跃市场，他们只能用模型为未上市股权的公允价值辩护。",
  },
  {
    id: "reconciliation",
    term: "reconciliation",
    phonetic: "/ˌrekənsɪliˈeɪʃn/",
    pos: "n.",
    topic: "finance",
    meaning: "对账：把两套记录核对到一致，如银行对账、系统对账。",
    grammar: "bank reconciliation。动词 reconcile A with B。",
    contextKind: "story",
    contextTitle: "月末",
    contextBody: "The bank reconciliation still showed a twenty-thousand gap, so they froze the close checklist.",
    contextZh: "银行对账仍差两万，所以他们冻结了关账清单。",
  },
  {
    id: "deferred-revenue",
    term: "deferred revenue",
    phonetic: "/dɪˈfɜːrd ˈrevənuː/",
    pos: "n.",
    topic: "finance",
    meaning: "递延收入：钱已收、履约义务尚未完成，先记负债。",
    grammar: "也叫 unearned revenue。确认时 recognize deferred revenue。",
    contextKind: "news",
    contextTitle: "SaaS 财报",
    contextBody: "Annual billings rose, but deferred revenue grew faster because multi-year contracts were prepaid.",
    contextZh: "年账单增加了，但递延收入涨得更快，因为多年合同是预付的。",
  },
  {
    id: "materiality",
    term: "materiality",
    phonetic: "/məˌtɪriˈæləti/",
    pos: "n.",
    topic: "finance",
    meaning: "重要性：错报大到可能影响使用者决策的阈值。",
    grammar: "material misstatement；形容词 material。",
    contextKind: "speech",
    contextTitle: "审计沟通",
    contextBody: "The adjustment was below materiality, yet the audit partner still wanted it booked for governance.",
    contextZh: "调整额低于重要性水平，但审计合伙人为了治理仍要求入账。",
  },
  {
    id: "going-concern",
    term: "going concern",
    phonetic: "/ˌɡoʊɪŋ kənˈsɜːrn/",
    pos: "n.",
    topic: "finance",
    meaning: "持续经营：假设企业能在可预见未来继续运营。",
    grammar: "going-concern assumption；substantial doubt about going concern。",
    contextKind: "news",
    contextTitle: "年审",
    contextBody: "Cash burn triggered a going concern discussion, even though the new facility was almost signed.",
    contextZh: "现金消耗引发了持续经营讨论，尽管新授信几乎已经签好。",
  },
  {
    id: "spread",
    term: "spread",
    phonetic: "/spred/",
    pos: "n.",
    topic: "finance",
    meaning: "利差/点差：两个收益率或买卖价之间的差额。",
    grammar: "credit spread、bid-ask spread。动词 spread 另有“传播”义。",
    contextKind: "news",
    contextTitle: "信用市场",
    contextBody: "Investment-grade spreads tightened, while high-yield names still paid for liquidity.",
    contextZh: "投资级利差收窄，高收益品种仍在为流动性付溢价。",
  },
  {
    id: "rollover",
    term: "rollover",
    phonetic: "/ˈroʊloʊvər/",
    pos: "n.",
    topic: "finance",
    meaning: "展期：把到期债务或头寸转到下一期。",
    grammar: "debt rollover；动词 roll over a loan。",
    contextKind: "speech",
    contextTitle: "司库会",
    contextBody: "We should not assume an automatic rollover; two lenders already asked for tighter terms.",
    contextZh: "我们不能默认会自动展期；已经有两家银行要求更严的条款。",
  },
  {
    id: "interoperability",
    term: "interoperability",
    phonetic: "/ˌɪntərɑːpərəˈbɪləti/",
    pos: "n.",
    topic: "informatization",
    meaning: "互操作性：不同系统能交换并共同使用数据的能力。",
    grammar: "不可数。形容词 interoperable。",
    contextKind: "speech",
    contextTitle: "架构评审",
    contextBody: "Without interoperability, the finance close still needed three manual exports every month.",
    contextZh: "没有互操作性，财务关账每个月仍要三次手工导出。",
  },
  {
    id: "middleware",
    term: "middleware",
    phonetic: "/ˈmɪdlwer/",
    pos: "n.",
    topic: "informatization",
    meaning: "中间件：应用与系统之间传递数据、调用服务的软件层。",
    grammar: "不可数。integration middleware。",
    contextKind: "story",
    contextTitle: "接口事故",
    contextBody: "When middleware queued invoices twice, accounts payable posted duplicate bills before anyone noticed.",
    contextZh: "中间件把发票排了两遍队，应付账款在有人发现前就入了重复账单。",
  },
  {
    id: "api-gateway",
    term: "API gateway",
    phonetic: "/ˌeɪ piː ˈaɪ ˈɡeɪtweɪ/",
    pos: "n.",
    topic: "informatization",
    meaning: "API 网关：统一鉴权、限流、路由的入口。",
    grammar: "API 作修饰语，常用大写。复数 gateways。",
    contextKind: "news",
    contextTitle: "平台升级",
    contextBody: "The new API gateway throttled partner traffic during month-end, which delayed bank-file uploads.",
    contextZh: "新 API 网关在月末限流了合作方流量，耽误了银行文件上传。",
  },
  {
    id: "idempotent",
    term: "idempotent",
    phonetic: "/aɪˈdempətənt/",
    pos: "adj.",
    topic: "informatization",
    meaning: "幂等：同一请求执行一次或多次，结果相同。",
    grammar: "idempotent request / idempotent key。名词 idempotency。",
    contextKind: "story",
    contextTitle: "支付重试",
    contextBody: "Because the payout API was not idempotent, a timeout plus a retry created two transfers.",
    contextZh: "因为付款接口不是幂等的，超时后再试产生了两笔转账。",
  },
  {
    id: "latency",
    term: "latency",
    phonetic: "/ˈleɪtənsi/",
    pos: "n.",
    topic: "informatization",
    meaning: "延迟：从发出请求到收到响应的时间。",
    grammar: "low latency、latency spike。不可数。",
    contextKind: "news",
    contextTitle: "交易系统",
    contextBody: "Matching-engine latency jumped at the open, and some quotes were stale for several milliseconds.",
    contextZh: "开盘时撮合引擎延迟跳升，部分报价有几毫秒是旧的。",
  },
  {
    id: "schema",
    term: "schema",
    phonetic: "/ˈskiːmə/",
    pos: "n.",
    topic: "informatization",
    meaning: "模式/结构：数据库或接口中字段如何组织的约定。",
    grammar: "复数 schemas 或 schemata。schema change。",
    contextKind: "story",
    contextTitle: "主数据",
    contextBody: "A silent schema change on vendor_id broke the reconciliation job that finance trusted each night.",
    contextZh: "vendor_id 上一次无声的结构变更，弄坏了财务每晚信赖的对账作业。",
  },
  {
    id: "orchestration",
    term: "orchestration",
    phonetic: "/ˌɔːrkɪˈstreɪʃn/",
    pos: "n.",
    topic: "informatization",
    meaning: "编排：按顺序或条件调度多个服务、任务或流程。",
    grammar: "workflow orchestration。动词 orchestrate。",
    contextKind: "speech",
    contextTitle: "数字化例会",
    contextBody: "Close orchestration now waits for tax, treasury, and revenue systems before it marks a period locked.",
    contextZh: "关账编排现在会等税务、司库和收入系统就绪，才把期间标为锁定。",
  },
  {
    id: "provenance",
    term: "provenance",
    phonetic: "/ˈprɑːvənəns/",
    pos: "n.",
    topic: "informatization",
    meaning: "数据出处：数据从哪里来、经过哪些处理。",
    grammar: "data provenance。不可数。",
    contextKind: "news",
    contextTitle: "监管问询",
    contextBody: "Regulators asked for provenance of the risk numbers, not just the final dashboard screenshot.",
    contextZh: "监管要的是风险数字的出处，而不只是仪表盘最后一张截图。",
  },
  {
    id: "canonical",
    term: "canonical",
    phonetic: "/kəˈnɑːnɪkl/",
    pos: "adj.",
    topic: "informatization",
    meaning: "权威的/标准的：被指定为唯一标准的数据或格式。",
    grammar: "canonical data model、canonical ID。",
    contextKind: "speech",
    contextTitle: "主数据治理",
    contextBody: "Customer is canonical in CRM; ERP must subscribe, not invent a second customer number.",
    contextZh: "客户以 CRM 为权威；ERP 应当订阅，而不是再发明一套客户编号。",
  },
  {
    id: "lineage",
    term: "lineage",
    phonetic: "/ˈlɪniɪdʒ/",
    pos: "n.",
    topic: "informatization",
    meaning: "血缘：数据从源系统到报表的流转路径。",
    grammar: "data lineage。与 provenance 相近，更强调路径图。",
    contextKind: "story",
    contextTitle: "指标对不上",
    contextBody: "They mapped lineage from the general ledger to the board pack and found a forgotten filter.",
    contextZh: "他们把总账到董事会材料的血缘画出来，发现了一个被遗忘的筛选条件。",
  },
  {
    id: "tokenization",
    term: "tokenization",
    phonetic: "/ˌtoʊkənaɪˈzeɪʃn/",
    pos: "n.",
    topic: "informatization",
    meaning: "令牌化：用令牌替换敏感数据，降低暴露面。",
    grammar: "tokenize card data。也用于 NLP 分词，这里取财务信息化义。",
    contextKind: "news",
    contextTitle: "支付合规",
    contextBody: "After tokenization, the data lake no longer stored raw PAN, which simplified the audit scope.",
    contextZh: "令牌化之后，数据湖不再存原始卡号，审计范围也简化了。",
  },
  {
    id: "zero-trust",
    term: "zero trust",
    phonetic: "/ˌzɪroʊ ˈtrʌst/",
    pos: "n./adj.",
    topic: "informatization",
    meaning: "零信任：默认不信任内外网络，每次访问都要验证。",
    grammar: "zero-trust architecture。作定语时常加连字符。",
    contextKind: "speech",
    contextTitle: "安全委员会",
    contextBody: "Zero trust means the close robot cannot pull the ledger just because it sits on the same VPN.",
    contextZh: "零信任意味着关账机器人不能只因为在同一 VPN 上就去拉总账。",
  },
  {
    id: "observability",
    term: "observability",
    phonetic: "/əbˌzɜːrvəˈbɪləti/",
    pos: "n.",
    topic: "informatization",
    meaning: "可观测性：通过日志、指标、追踪判断系统内部状态。",
    grammar: "不可数。形容词 observable。",
    contextKind: "story",
    contextTitle: "夜间批处理",
    contextBody: "Better observability showed the ETL stalling on one vendor file, hours before the close team arrived.",
    contextZh: "更好的可观测性显示 ETL 卡在一个供应商文件上，比关账团队上班早了几个小时。",
  },
  {
    id: "backfill",
    term: "backfill",
    phonetic: "/ˈbækfɪl/",
    pos: "v./n.",
    topic: "informatization",
    meaning: "回填：补跑历史数据或补齐缺失期间的记录。",
    grammar: "backfill a pipeline；名词 a three-year backfill。",
    contextKind: "news",
    contextTitle: "数据迁移",
    contextBody: "The warehouse backfill of invoices took a weekend, and tax reports had to wait until Monday.",
    contextZh: "数仓回填发票花了一个周末，税务报表只能等到周一。",
  },
  {
    id: "sla",
    term: "SLA",
    phonetic: "/ˌes el ˈeɪ/",
    pos: "n.",
    topic: "informatization",
    meaning: "服务级别协议：对可用性、时效等承诺的合同条款。",
    grammar: "service-level agreement。breach an SLA。",
    contextKind: "speech",
    contextTitle: "供应商管理",
    contextBody: "If the bank-file SLA slips past 9 a.m., payroll and vendor payments both miss the window.",
    contextZh: "如果银行文件的 SLA 拖过上午九点，工资和供应商付款都会错过窗口。",
  },
  {
    id: "failover",
    term: "failover",
    phonetic: "/ˈfeɪloʊvər/",
    pos: "n.",
    topic: "informatization",
    meaning: "故障切换：主系统不可用时自动切到备用。",
    grammar: "failover test；动词 fail over to the secondary site。",
    contextKind: "story",
    contextTitle: "演练",
    contextBody: "During failover, the payment gateway stayed up, but the reporting replica lagged by twelve minutes.",
    contextZh: "故障切换时支付网关还在，但报表副本落后了十二分钟。",
  },
  {
    id: "rbac",
    term: "RBAC",
    phonetic: "/ˌɑːr biː eɪ ˈsiː/",
    pos: "n.",
    topic: "informatization",
    meaning: "基于角色的访问控制：按角色授权，而不是给每个人单独开权限。",
    grammar: "role-based access control。implement RBAC。",
    contextKind: "news",
    contextTitle: "内控",
    contextBody: "RBAC stopped junior analysts from posting journals, which the auditors had flagged last year.",
    contextZh: "基于角色的访问控制拦住了初级分析师过账，这正是审计去年指出的问题。",
  },
  {
    id: "event-driven",
    term: "event-driven",
    phonetic: "/ɪˈvent ˌdrɪvn/",
    pos: "adj.",
    topic: "informatization",
    meaning: "事件驱动：系统因事件发生而触发处理，而不是靠定时批量。",
    grammar: "event-driven architecture。连字符形容词。",
    contextKind: "speech",
    contextTitle: "中台规划",
    contextBody: "An event-driven ledger update can post cash the moment the bank confirms, not at tonight's batch.",
    contextZh: "事件驱动的总账更新可以在银行确认的瞬间入账，而不必等到今晚的批处理。",
  },
  {
    id: "data-mart",
    term: "data mart",
    phonetic: "/ˈdeɪtə mɑːrt/",
    pos: "n.",
    topic: "informatization",
    meaning: "数据集市：面向某个部门或主题的精简数据集合。",
    grammar: "finance data mart。比 data warehouse 更窄。",
    contextKind: "story",
    contextTitle: "自助分析",
    contextBody: "The FP&A data mart finally matched the ledger, so weekend spreadsheet merges became rare.",
    contextZh: "FP&A 数据集市终于和总账对上了，周末拼表变得很少。",
  },
  {
    id: "encryption-at-rest",
    term: "encryption at rest",
    phonetic: "/ɪnˈkrɪpʃn ət rest/",
    pos: "n.",
    topic: "informatization",
    meaning: "静态加密：数据存储时加密，区别于传输中加密。",
    grammar: "encryption in transit / encryption at rest。",
    contextKind: "news",
    contextTitle: "云合规",
    contextBody: "Encryption at rest was enabled on the archive bucket before payroll files were moved off the file share.",
    contextZh: "工资文件从共享盘迁走前，归档桶已开启静态加密。",
  },
  {
    id: "throughput",
    term: "throughput",
    phonetic: "/ˈθruːpʊt/",
    pos: "n.",
    topic: "informatization",
    meaning: "吞吐量：单位时间内系统能处理的请求或交易量。",
    grammar: "不可数。high throughput。与 latency 常成对出现。",
    contextKind: "speech",
    contextTitle: "容量规划",
    contextBody: "Month-end throughput on the invoice API must double, or AP clerks will wait on a spinner again.",
    contextZh: "月末发票接口的吞吐量必须翻倍，否则应付会计又要盯着转圈。",
  },
  {
    id: "single-source-of-truth",
    term: "single source of truth",
    phonetic: "/ˌsɪŋɡl sɔːrs əv truːθ/",
    pos: "n.",
    topic: "informatization",
    meaning: "单一事实来源：一个指标只认一个权威系统。",
    grammar: "缩写 SSOT。作名词短语。",
    contextKind: "speech",
    contextTitle: "经营分析会",
    contextBody: "Revenue has one single source of truth in billing; marketing dashboards must not calculate their own.",
    contextZh: "收入以计费系统为单一事实来源；营销看板不得自己另算一套。",
  },
  {
    id: "change-management",
    term: "change management",
    phonetic: "/tʃeɪndʒ ˈmænɪdʒmənt/",
    pos: "n.",
    topic: "informatization",
    meaning: "变更管理：控制系统改动的申请、审批、发布与回滚。",
    grammar: "不可数。a change-management ticket。",
    contextKind: "story",
    contextTitle: "热修",
    contextBody: "They skipped change management to fix a close job, then spent Friday proving what had been released.",
    contextZh: "他们跳过变更管理去修关账作业，然后周五花了一天证明到底发了什么。",
  },
  {
    id: "kpi",
    term: "KPI",
    phonetic: "/ˌkeɪ piː ˈaɪ/",
    pos: "n.",
    topic: "finance",
    meaning: "关键绩效指标：衡量目标进展的核心度量。",
    grammar: "key performance indicator。复数 KPIs。",
    contextKind: "news",
    contextTitle: "经营月报",
    contextBody: "Cash conversion cycle became a board KPI after working capital slipped two quarters in a row.",
    contextZh: "营运资本连续两个季度走弱后，现金周转周期成了董事会的 KPI。",
  },
  {
    id: "runway",
    term: "runway",
    phonetic: "/ˈrʌnweɪ/",
    pos: "n.",
    topic: "finance",
    meaning: "现金跑道：按当前消耗还能支撑多少个月。",
    grammar: "cash runway。eighteen months of runway。",
    contextKind: "speech",
    contextTitle: "融资准备",
    contextBody: "With current burn, runway is fourteen months, unless collections on enterprise deals improve.",
    contextZh: "按当前消耗，现金跑道是十四个月，除非大客户回款改善。",
  },
  {
    id: "soxd",
    term: "SOX",
    phonetic: "/sɑːks/",
    pos: "n.",
    topic: "finance",
    meaning: "萨班斯法案：要求上市公司内控与财务报告责任的美国法规。",
    grammar: "SOX compliance、SOX control。作专有名词。",
    contextKind: "news",
    contextTitle: "内控测试",
    contextBody: "The SOX walkthrough failed because the journal approver could also post in the same role.",
    contextZh: "SOX 穿行测试失败，因为凭证审批人还能用同一角色过账。",
  },
  {
    id: "master-data",
    term: "master data",
    phonetic: "/ˈmæstər ˈdeɪtə/",
    pos: "n.",
    topic: "informatization",
    meaning: "主数据：客户、物料、科目等跨系统共享的核心档案。",
    grammar: "不可数。master data management (MDM)。",
    contextKind: "story",
    contextTitle: "编码冲突",
    contextBody: "Two plants used different vendor master data, so spend reports double-counted the same supplier.",
    contextZh: "两家工厂用了不同的供应商主数据，支出报表把同一家供应商算了两遍。",
  },
  {
    id: "straight-through-processing",
    term: "straight-through processing",
    phonetic: "/streɪt θruː ˈprɑːsesɪŋ/",
    pos: "n.",
    topic: "informatization",
    meaning: "直通处理：交易从发起到入账尽量无人干预自动完成。",
    grammar: "缩写 STP。不可数。",
    contextKind: "news",
    contextTitle: "结算升级",
    contextBody: "Straight-through processing cut the exception queue, but fat-finger trades still needed a human hold.",
    contextZh: "直通处理缩短了异常队列，但误操作交易仍需要人工拦截。",
  },
];
